/**
 * parcels.js — Data layer for the Hawaiʻi Ceded Lands Back Rent Calculator
 *
 * All parcel acreages, rental benchmarks, CPI series, and primary source
 * references are maintained here, separate from the application logic.
 *
 * DATA SOURCES:
 *   - EO 11167 (Aug 15, 1964): 84,057 ac at PTA
 *   - EO 11166 (Aug 15, 1964): 3,236 ac at Makua
 *   - EO 11165 (Aug 15, 1964): 0.5 ac at Fort Shafter
 *   - 1969 "Public Land Policy in Hawaii: An Historical Analysis", Table 9
 *   - DLNR Report to the 33rd Legislature (2026 Regular Session)
 *   - HMLUMP 2021 (221,981 ac total statewide)
 *   - Cultural Survival / Noho Hewa (112,173 ac ceded = 54%)
 *   - DoD Base Structure Reports; Wikipedia; Army/Navy MWR records
 *   - State of Hawaii GIS: DoD Lands Layer (Oct 2025)
 *   - Admission Act §5(b), §5(d), §5(f)
 *
 * ACREAGE CONFIDENCE:
 *   "hard"   = from executive order text, legislative record, or 1969 Table 9
 *   "firm"   = from base records, Wikipedia with citations, or HMLUMP maps
 *   "approx" = estimated from HMLUMP context, Noho Hewa, or secondary sources
 */

// ═══════════════════════════════════════════════════════════════════════
// PARCELS
// ═══════════════════════════════════════════════════════════════════════

export const PARCELS = [

  // ─── FEDERAL-OWNED CEDED LANDS (seized / set aside / retained) ─────

  {
    id: "pta_federal",
    name: "Pohakuloa Training Area (Federal Parcel)",
    island: "Hawaii Island",
    acres: 84057,
    confidence: "hard",
    tenure: "federal_owned",
    acquisitionYear: 1964,
    acquisitionMethod: "Presidential Executive Order 11167",
    startYear: 1964,
    cededLand: true,
    notes: "EO 11167 (LBJ, Aug 15, 1964) set aside 84,057 ac of Crown Land of Humu'ula and Government Lands of Kaohe/Pu'uanahulu. Largest single federal seizure of ceded land. Contains 51,000-ac impact area with depleted uranium contamination.",
    zoning: "conservation",
    category: "federal",
    cercla: { epaId: "HI3214522234", siteNo: "0904485", npl: false, status: "Site Inspection Review Start Needed", contaminants: ["UXO", "depleted uranium", "range contaminants"], url: "https://cumulis.epa.gov/supercpad/cursites/csitinfo.cfm?id=0904485" },
    sources: [
      { label: "EO 11167 Full Text", url: "https://www.presidency.ucsb.edu/documents/executive-order-11167-setting-aside-for-the-use-the-united-states-certain-public-lands-and" },
      { label: "Final EIS (2025)", url: "https://www.federalregister.gov/documents/2025/04/18/2025-06686/final-environmental-impact-statement-for-army-training-land-retention-at-phakuloa-training-area-in" },
      { label: "BLNR Rejects EIS (May 2025)", url: "https://dlnr.hawaii.gov/blog/2025/05/10/nr25-71/" },
      { label: "Record of Decision (Aug 2025)", url: "https://www.federalregister.gov/documents/2025/08/06/2025-14919/record-of-decision-for-army-training-land-retention-at-phakuloa-training-area-in-hawaii-id" },
      { label: "1969 Historical Analysis, Table 9", url: "" },
    ],
  },
  {
    id: "schofield",
    name: "Schofield Barracks & East Range",
    island: "Oahu",
    acres: 17725,
    confidence: "firm",
    tenure: "federal_owned",
    acquisitionYear: 1908,
    acquisitionMethod: "EO of July 20, 1899 (McKinley), retained per 5(d)",
    startYear: 1908,
    cededLand: true,
    notes: "Established 1908 on ceded Crown/Government lands. Largest Army post in Hawaii. Home of 25th Infantry Division.",
    zoning: "military",
    category: "federal",
    cercla: { epaId: "HI2210020774", siteNo: "0902923", npl: "deleted", nplNote: "Deleted from NPL in 2000", status: "Completed", contaminants: ["TCE", "VOCs", "asbestos"], url: "https://cumulis.epa.gov/supercpad/cursites/csitinfo.cfm?id=0902923" },
    sources: [
      { label: "Wikipedia (17,725 ac)", url: "https://en.wikipedia.org/wiki/Schofield_Barracks" },
      { label: "Military.com", url: "https://www.military.com/base-guide/schofield-barracksfort-shafter" },
    ],
  },
  {
    id: "jbphh",
    name: "Joint Base Pearl Harbor-Hickam",
    island: "Oahu",
    acres: 12200,
    confidence: "approx",
    tenure: "federal_owned",
    acquisitionYear: 1887,
    acquisitionMethod: "Ceded at annexation (1898), retained per 5(d)",
    startYear: 1898,
    cededLand: true,
    notes: "Pearl Harbor ceded 1887 (reciprocity treaty). Hickam est. 1935. 6 Superfund sites. Red Hill fuel spill contaminated drinking water (2021). Ke'awalau o Pu'uloa once supported 36+ fishponds. Acreage excludes Ford Island (counted separately).",
    zoning: "military",
    category: "federal",
    cercla: { epaId: "HI4170090076", siteNo: "0904481", npl: true, status: "Active — investigations and remedial actions ongoing across 18 Geographic Study Areas", contaminants: ["arsenic", "chlorinated solvents", "lead", "PAHs", "PCBs", "pesticides", "petroleum hydrocarbons", "PFAS"], url: "https://cumulis.epa.gov/supercpad/cursites/csitinfo.cfm?id=0904481" },
    sources: [
      { label: "Cultural Survival", url: "https://www.culturalsurvival.org/publications/cultural-survival-quarterly/nation-under-gun-militarism-and-resistance-hawaii" },
      { label: "Hawaii Business", url: "https://www.hawaiibusiness.com/hawaiian-kingdom-ceded-lands-history-debate-solutions/" },
    ],
  },
  {
    id: "ford_island",
    name: "Ford Island (Moku'ume'ume)",
    island: "Oahu",
    acres: 441,
    confidence: "firm",
    tenure: "federal_owned",
    acquisitionYear: 1916,
    acquisitionMethod: "Purchased by US Navy 1916; enlarged to 441 ac by 1940 dredge fill",
    startYear: 1916,
    cededLand: true,
    notes: "Island inside Pearl Harbor. Originally 334 ac, enlarged to 441 ac with dredge fill. Site of Battleship Row. USS Arizona and USS Missouri memorials. Ancient Hawaiian name Moku'ume'ume ('isle of attraction').",
    zoning: "military",
    category: "federal",
    sources: [
      { label: "Wikipedia: Ford Island (441 ac)", url: "https://en.wikipedia.org/wiki/Ford_Island" },
      { label: "pearlharbor.org", url: "https://pearlharbor.org/blog/ford-island-hawaii/" },
    ],
  },
  {
    id: "mcbh",
    name: "Marine Corps Base Hawaii (Kane'ohe Bay / Mokapu)",
    island: "Oahu",
    acres: 2951,
    confidence: "firm",
    tenure: "federal_owned",
    acquisitionYear: 1941,
    acquisitionMethod: "Wartime seizure of ceded land, retained per 5(d)",
    startYear: 1941,
    cededLand: true,
    notes: "Mokapu Peninsula. Hundreds of iwi kupuna unearthed by military housing construction. Ceded Crown lands seized during WWII.",
    zoning: "military",
    category: "federal",
    cercla: { epaId: "HI6170022762", siteNo: "0902919", npl: false, status: "Federal Facility-Lead Cleanup", contaminants: ["PCBs", "stormwater discharge violations"], url: "https://cumulis.epa.gov/supercpad/cursites/csitinfo.cfm?id=0902919" },
    sources: [
      { label: "Cultural Survival", url: "https://www.culturalsurvival.org/publications/cultural-survival-quarterly/nation-under-gun-militarism-and-resistance-hawaii" },
    ],
  },
  {
    id: "wheeler",
    name: "Wheeler Army Airfield",
    island: "Oahu",
    acres: 1389,
    confidence: "firm",
    tenure: "federal_owned",
    acquisitionYear: 1922,
    acquisitionMethod: "Federal reservation on ceded land, retained per 5(d)",
    startYear: 1922,
    cededLand: true,
    notes: "Adjacent to Schofield Barracks. Est. 1922 on ceded Government lands. Primary Army aviation facility.",
    zoning: "military",
    category: "federal",
    cercla: { epaId: "HI3573028732", siteNo: "0902917", npl: false, status: "Federal Facility-Lead Cleanup", contaminants: ["PFAS"], url: "https://cumulis.epa.gov/supercpad/cursites/csitinfo.cfm?id=0902917" },
    sources: [
      { label: "HMLUMP 2021", url: "https://drive.google.com/file/d/1Uov0HevmHkfMG-ma-iEzxYgECHue67aY/view" },
    ],
  },
  {
    id: "lualualei",
    name: "Naval Magazine Lualualei",
    island: "Oahu",
    acres: 8200,
    confidence: "approx",
    tenure: "federal_owned",
    acquisitionYear: 1931,
    acquisitionMethod: "Executive Order on ceded land, retained per 5(d)",
    startYear: 1931,
    cededLand: true,
    notes: "Ammunition storage. 1,356 ac improperly withdrawn from Hawaiian Home Lands. 1999 land swap gave DHHL only 580 ac at Barber's Point — net loss of 770 ac from Native land base.",
    zoning: "military",
    category: "federal",
    cercla: { epaId: "HI9170090006", siteNo: "0902926", npl: true, status: "Active — Federal Facility Agreement (2009) with EPA and Hawaii DOH", contaminants: ["ordnance-related contamination"], url: "https://cumulis.epa.gov/supercpad/cursites/calinfo.cfm?id=0902926" },
    sources: [
      { label: "Cultural Survival", url: "https://www.culturalsurvival.org/publications/cultural-survival-quarterly/nation-under-gun-militarism-and-resistance-hawaii" },
      { label: "HMLUMP 2021", url: "https://drive.google.com/file/d/1Uov0HevmHkfMG-ma-iEzxYgECHue67aY/view" },
    ],
  },
  {
    id: "fort_shafter",
    name: "Fort Shafter / Camp Smith",
    island: "Oahu",
    acres: 798,
    confidence: "firm",
    tenure: "federal_owned",
    acquisitionYear: 1907,
    acquisitionMethod: "EO of July 20, 1899; EO 2521 (1917); EO 11165 (1964, +0.5 ac)",
    startYear: 1907,
    cededLand: true,
    notes: "Fort Shafter (~574 ac) est. 1907, HQ US Army Pacific. Camp Smith (224 ac) HQ US Indo-Pacific Command. EO 11165 set aside 0.5 additional ac in 1964.",
    zoning: "military",
    category: "federal",
    cercla: { epaId: "HI6214522207", siteNo: "0902921", npl: false, status: "Site Inspection Review Start Needed", contaminants: ["asbestos"], url: "https://cumulis.epa.gov/supercpad/cursites/csitinfo.cfm?id=0902921" },
    sources: [
      { label: "EO 11165 (1964)", url: "https://www.presidency.ucsb.edu/documents/executive-order-11165-setting-aside-for-the-use-the-united-states-certain-public-lands-and" },
      { label: "EO 2521 / 10404 (Shafter)", url: "https://www.presidency.ucsb.edu/documents/executive-order-10404-resorting-certain-land-reserved-for-military-purposes-the-territory" },
    ],
  },
  {
    id: "pmrf_federal",
    name: "Pacific Missile Range Facility (Federal Parcel)",
    island: "Kauai",
    acres: 3600,
    confidence: "approx",
    tenure: "federal_owned",
    acquisitionYear: 1940,
    acquisitionMethod: "Wartime seizure, retained per 5(d)",
    startYear: 1940,
    cededLand: true,
    notes: "Barking Sands. Navy's primary missile testing range in Pacific. Includes oceanfront land at Nohili.",
    zoning: "military",
    category: "federal",
    cercla: { epaId: "HI6170024719", siteNo: "0900204", npl: false, status: "NFRAP — does not qualify based on existing information", contaminants: ["PFAS/AFFF"], url: "https://cumulis.epa.gov/supercpad/cursites/csitinfo.cfm?id=0900204" },
    sources: [
      { label: "OHA: Military Leased Lands", url: "https://www.oha.org/aloha-aina/" },
      { label: "HMLUMP 2021", url: "https://drive.google.com/file/d/1Uov0HevmHkfMG-ma-iEzxYgECHue67aY/view" },
    ],
  },
  {
    id: "makua_federal",
    name: "Makua Military Reservation (Federal Parcel)",
    island: "Oahu",
    acres: 3236,
    confidence: "hard",
    tenure: "federal_owned",
    acquisitionYear: 1943,
    acquisitionMethod: "EO 11166 (Aug 15, 1964) — 3,236 ac of Government Lands of Makua and Kahanahaiki",
    startYear: 1943,
    cededLand: true,
    notes: "Sacred valley. Families forcibly evicted during WWII — never allowed return. Live-fire suspended since 2004 per court order.",
    zoning: "conservation",
    category: "federal",
    cercla: { epaId: "HI7210022227", siteNo: "0900212", npl: false, status: "Active — UXO sweeps and PFAS assessment", contaminants: ["UXO", "RDX", "2,4-DNT", "2,6-DNT", "PFAS/AFFF"], url: "https://cumulis.epa.gov/supercpad/cursites/calinfo.cfm?id=0900212" },
    sources: [
      { label: "EO 11166 (1964)", url: "https://www.presidency.ucsb.edu/documents/executive-order-11166-setting-aside-for-the-use-the-united-states-certain-public-lands-and" },
      { label: "1969 Historical Analysis, Table 9", url: "" },
      { label: "Malama Makua", url: "https://www.malamamakua.org/" },
      { label: "Noho Hewa", url: "https://nohohewa.com/occupied-areas/" },
    ],
  },
  {
    id: "bellows_federal",
    name: "Bellows Air Force Station (Federal Parcel)",
    island: "Oahu",
    acres: 1500,
    confidence: "firm",
    tenure: "federal_owned",
    acquisitionYear: 1917,
    acquisitionMethod: "Federal reservation on ceded/HHCA land, retained per 5(d)",
    startYear: 1917,
    cededLand: true,
    notes: "Waimanalo beachfront. Includes land improperly withdrawn from Hawaiian Home Lands. Some of Oahu's most valuable beachfront.",
    zoning: "mixed",
    category: "federal",
    cercla: { epaId: "HI3570028719", siteNo: "0902916", npl: false, status: "Federal Facility-Lead Cleanup", contaminants: [], url: "https://cumulis.epa.gov/supercpad/cursites/csitinfo.cfm?id=0902916" },
    sources: [
      { label: "Bellows AFS ROD (1996)", url: "https://www.govinfo.gov/content/pkg/FR-1996-06-05/html/96-14067.htm" },
      { label: "HMLUMP 2021", url: "https://drive.google.com/file/d/1Uov0HevmHkfMG-ma-iEzxYgECHue67aY/view" },
    ],
  },
  {
    id: "fort_derussy",
    name: "Fort DeRussy (Waikiki)",
    island: "Oahu",
    acres: 72,
    confidence: "firm",
    tenure: "federal_owned",
    acquisitionYear: 1906,
    acquisitionMethod: "US War Dept acquired 70+ ac in Kalia, Waikiki (1904-1906)",
    startYear: 1906,
    cededLand: true,
    notes: "Waikiki beachfront. Hale Koa Hotel (Armed Forces Recreation Center), Army Museum, Asia-Pacific Center for Security Studies. Among the most valuable beachfront real estate in the world. Originally purchased from Chun Afong estate for $28,000.",
    zoning: "military",
    category: "federal",
    sources: [
      { label: "Wikipedia: Fort DeRussy", url: "https://en.wikipedia.org/wiki/Fort_DeRussy_Military_Reservation" },
      { label: "Images of Old Hawaii", url: "https://imagesofoldhawaii.com/fort-derussy/" },
      { label: "Fort DeRussy Hawaii", url: "https://www.fortderussyhawaii.com/fort-derussy-history" },
    ],
  },
  {
    id: "aliamanu",
    name: "Aliamanu Military Reservation (Housing)",
    island: "Oahu",
    acres: 524,
    confidence: "firm",
    tenure: "federal_owned",
    acquisitionYear: 1956,
    acquisitionMethod: "Federal reservation in volcanic crater, ceded land",
    startYear: 1956,
    cededLand: true,
    notes: "524-ac volcanic crater. Joint Army-Navy housing for 2,600 families (11,500 people). Designed by Beverly Willis, 1974. Crater floor formerly filled with gun/cannon shells.",
    zoning: "military",
    category: "federal",
    sources: [
      { label: "Beverly Willis Archive (524 ac)", url: "https://beverlywillis.com/architecture-project/0660/" },
      { label: "Noho Hewa", url: "https://nohohewa.com/occupied-areas/" },
    ],
  },
  {
    id: "dillingham",
    name: "Dillingham Military Reservation",
    island: "Oahu",
    acres: 650,
    confidence: "firm",
    tenure: "federal_owned",
    acquisitionYear: 1922,
    acquisitionMethod: "Camp Kawaihapai est. 1922 (67 ac); expanded to 650 ac by 1946",
    startYear: 1922,
    cededLand: true,
    notes: "North Shore. Army airfield, 9,000-ft runway. HDOT leases 272 ac for civilian glider/skydiving operations. 50-year lease signed July 2024. Originally Camp Kawaihapai (communications station).",
    zoning: "military",
    category: "federal",
    sources: [
      { label: "HDOT: Kawaihapai Airfield (650-ac reservation)", url: "https://airports.hawaii.gov/hdh/" },
      { label: "GlobalSecurity.org", url: "https://www.globalsecurity.org/military/facility/dillingham.htm" },
      { label: "Wikipedia: Mokuleia Army Airfield", url: "https://en.wikipedia.org/wiki/Mokuleia_Army_Airfield" },
    ],
  },
  {
    id: "fort_ruger",
    name: "Fort Ruger / Diamond Head (Retained Portion)",
    island: "Oahu",
    acres: 80,
    confidence: "approx",
    tenure: "federal_owned",
    acquisitionYear: 1906,
    acquisitionMethod: "EO 395-A (Jan 18, 1906); 755 ac reserved; most returned to Territory/State",
    startYear: 1906,
    cededLand: true,
    notes: "Originally 755 ac (1906). Army transferred most to Territory/State by 1955. Hawaii National Guard retains ~80 ac. Diamond Head State Monument (475 ac) now under DLNR. First military reservation in Territory of Hawaii.",
    zoning: "military",
    category: "federal",
    sources: [
      { label: "HI Dept of Defense: Fort Ruger History", url: "https://dod.hawaii.gov/blog/fort-ruger-and-the-hawaii-national-guard/" },
      { label: "Wikipedia: Fort Ruger", url: "https://en.wikipedia.org/wiki/Fort_Ruger" },
      { label: "EO 10453 (returning portions)", url: "https://www.presidency.ucsb.edu/documents/executive-order-10453-restoring-certain-lands-comprising-portions-the-fort-ruger-military" },
    ],
  },
  {
    id: "tripler",
    name: "Tripler Army Medical Center",
    island: "Oahu",
    acres: 234,
    confidence: "approx",
    tenure: "federal_owned",
    acquisitionYear: 1907,
    acquisitionMethod: "Federal reservation on ceded land, retained per 5(d)",
    startYear: 1907,
    cededLand: true,
    notes: "Moanalua ridge. Largest military hospital in the Pacific. Distinctive pink building visible from most of Honolulu. Originally part of Fort Shafter reservation.",
    zoning: "military",
    category: "federal",
    sources: [
      { label: "Noho Hewa", url: "https://nohohewa.com/occupied-areas/" },
    ],
  },
  {
    id: "helemano",
    name: "Helemano Military Reservation (Housing)",
    island: "Oahu",
    acres: 200,
    confidence: "approx",
    tenure: "federal_owned",
    acquisitionYear: 1942,
    acquisitionMethod: "Wartime seizure on ceded land, retained per 5(d)",
    startYear: 1942,
    cededLand: true,
    notes: "North of Wahiawa. 600+ family housing units. Home to 125th Signal Battalion. Surrounded by former pineapple fields.",
    zoning: "military",
    category: "federal",
    sources: [
      { label: "RealHawaii: Installations", url: "https://realhawaii.co/military-guide/installations" },
      { label: "Noho Hewa", url: "https://nohohewa.com/occupied-areas/" },
    ],
  },
  {
    id: "iroquois_point",
    name: "Iroquois Point / Pu'uloa Housing",
    island: "Oahu",
    acres: 490,
    confidence: "approx",
    tenure: "federal_owned",
    acquisitionYear: 1941,
    acquisitionMethod: "Wartime expansion of Pearl Harbor complex, ceded land",
    startYear: 1941,
    cededLand: true,
    notes: "Navy housing area at entrance to Pearl Harbor. Pu'uloa was one of the most productive fishpond regions in pre-contact Hawaii.",
    zoning: "military",
    category: "federal",
    sources: [
      { label: "Noho Hewa", url: "https://nohohewa.com/occupied-areas/" },
    ],
  },
  {
    id: "red_hill",
    name: "Red Hill Bulk Fuel Storage",
    island: "Oahu",
    acres: 100,
    confidence: "approx",
    tenure: "federal_owned",
    acquisitionYear: 1940,
    acquisitionMethod: "WWII-era underground fuel storage on ceded land",
    startYear: 1940,
    cededLand: true,
    notes: "20 underground steel-lined tanks holding 250M gallons of fuel. Nov 2021 fuel leak contaminated Oahu drinking water for ~93,000 people. Defueling completed 2024. Facility to be permanently closed.",
    zoning: "military",
    category: "federal",
    cercla: { epaId: "HI4170090076", siteNo: "0904481", npl: true, nplNote: "Part of Pearl Harbor Naval Complex NPL site", status: "Active — defueling completed 2024, permanent closure pending", contaminants: ["jet fuel (JP-5)", "petroleum hydrocarbons", "PFAS"], url: "https://cumulis.epa.gov/supercpad/cursites/csitinfo.cfm?id=0904481" },
    sources: [
      { label: "Noho Hewa", url: "https://nohohewa.com/occupied-areas/" },
    ],
  },
  {
    id: "kipapa",
    name: "Kipapa Ammunition Storage",
    island: "Oahu",
    acres: 60,
    confidence: "approx",
    tenure: "federal_owned",
    acquisitionYear: 1942,
    acquisitionMethod: "Wartime seizure on ceded land",
    startYear: 1942,
    cededLand: true,
    notes: "Ammunition storage facility in central Oahu.",
    zoning: "military",
    category: "federal",
    sources: [
      { label: "Noho Hewa", url: "https://nohohewa.com/occupied-areas/" },
    ],
  },
  {
    id: "kunia",
    name: "Kunia Field Station (NSA Hawaii)",
    island: "Oahu",
    acres: 50,
    confidence: "approx",
    tenure: "federal_owned",
    acquisitionYear: 1942,
    acquisitionMethod: "WWII-era tunnel facility on ceded land, retained per 5(d)",
    startYear: 1942,
    cededLand: true,
    notes: "Underground intelligence facility. Originally WWII-era tunnel complex. Now operated by NSA.",
    zoning: "military",
    category: "federal",
    sources: [
      { label: "Noho Hewa", url: "https://nohohewa.com/occupied-areas/" },
    ],
  },
  {
    id: "kaena_point",
    name: "Ka'ena Point Satellite Tracking Station",
    island: "Oahu",
    acres: 100,
    confidence: "approx",
    tenure: "federal_owned",
    acquisitionYear: 1958,
    acquisitionMethod: "Federal reservation on ceded land",
    startYear: 1958,
    cededLand: true,
    notes: "Air Force satellite tracking facility at Ka'ena Point, western tip of Oahu. Adjacent to Ka'ena Point State Park / Natural Area Reserve with endangered Hawaiian monk seals and Laysan albatross.",
    zoning: "military",
    category: "federal",
    sources: [
      { label: "Noho Hewa", url: "https://nohohewa.com/occupied-areas/" },
    ],
  },
  {
    id: "kmc",
    name: "Kilauea Military Camp (Hawaii Volcanoes NP)",
    island: "Hawaii Island",
    acres: 52,
    confidence: "firm",
    tenure: "federal_owned",
    acquisitionYear: 1916,
    acquisitionMethod: "Special Use Permit within HVNP; Army MWR recreation facility",
    startYear: 1916,
    cededLand: true,
    notes: "52-ac Armed Forces Recreation Center inside Hawaii Volcanoes National Park. 90 cottages. Bowling alley, restaurant, gas station. Est. 1916 — same year as the National Park. Served as WWII internment/POW camp.",
    zoning: "conservation",
    category: "federal",
    sources: [
      { label: "Wikipedia: Kilauea Military Camp", url: "https://en.wikipedia.org/wiki/Kilauea_Military_Camp" },
      { label: "Army MWR", url: "https://hawaii.armymwr.com/programs/kilauea-military-camp-kmc" },
    ],
  },
  {
    id: "kawaihae",
    name: "Kawaihae Military Reservation",
    island: "Hawaii Island",
    acres: 100,
    confidence: "approx",
    tenure: "federal_owned",
    acquisitionYear: 1942,
    acquisitionMethod: "Wartime seizure, ceded land",
    startYear: 1942,
    cededLand: true,
    notes: "Army landing site and logistics facility. Used for equipment transport to Pohakuloa Training Area via Saddle Road.",
    zoning: "military",
    category: "federal",
    sources: [
      { label: "Noho Hewa", url: "https://nohohewa.com/occupied-areas/" },
    ],
  },
  {
    id: "keaukaha",
    name: "Keaukaha Military Reservation (Hilo)",
    island: "Hawaii Island",
    acres: 50,
    confidence: "approx",
    tenure: "federal_owned",
    acquisitionYear: 1942,
    acquisitionMethod: "Wartime seizure, ceded land",
    startYear: 1942,
    cededLand: true,
    notes: "Army facility in Hilo. Home to Army Reserve and National Guard units.",
    zoning: "military",
    category: "federal",
    sources: [
      { label: "Noho Hewa", url: "https://nohohewa.com/occupied-areas/" },
    ],
  },

  // ─── RETURNED LANDS ────────────────────────────────────────────────

  {
    id: "kahoolawe",
    name: "Kaho'olawe (Former Federal — Returned 1994)",
    island: "Kaho'olawe",
    acres: 28800,
    confidence: "hard",
    tenure: "returned",
    acquisitionYear: 1941,
    acquisitionMethod: "Navy seizure (1941), returned to State 1994",
    startYear: 1941,
    endOverride: 1994,
    cededLand: true,
    notes: "Sacred island seized by Navy 1941. Bombed 53 years. Returned 1994. Congress provided $400M for partial cleanup (75% surface). Entire island on National Register. Still largely unusable.",
    zoning: "conservation",
    category: "returned",
    cercla: { epaId: "HI6170090074", siteNo: "0904432", npl: false, status: "Preliminary Assessment Review Start Needed — 75% surface cleared, ~9% subsurface cleared, ~30% not cleared", contaminants: ["UXO", "heavy metals", "explosives residue"], url: "https://cumulis.epa.gov/supercpad/cursites/csitinfo.cfm?id=0904432" },
    sources: [
      { label: "EO 10436 (Kahoolawe)", url: "https://www.presidency.ucsb.edu/documents/executive-order-10436-reserving-kahoolawe-island-territory-hawaii-for-the-use-the-united" },
      { label: "Noho Hewa", url: "https://nohohewa.com/occupied-areas/" },
      { label: "Wikipedia: Ceded Lands", url: "https://en.wikipedia.org/wiki/Ceded_lands_(Hawaii)" },
    ],
  },

  // ─── STATE-LEASED CEDED LANDS ($1 / 65 years, expiring 2029) ──────

  {
    id: "pta_leased",
    name: "Pohakuloa Training Area (State Lease)",
    island: "Hawaii Island",
    acres: 22971,
    confidence: "hard",
    tenure: "state_leased",
    acquisitionYear: 1964,
    acquisitionMethod: "65-year lease from DLNR at $1 total",
    startYear: 1964,
    leaseEnd: 2029,
    leaseCost: 1,
    cededLand: true,
    notes: "22,971 ac (3 parcels). Connective tissue between federal parcels. Conservation-zoned. BLNR rejected FEIS May 2025.",
    zoning: "conservation",
    category: "leased",
    sources: [
      { label: "DLNR 2026 Leg Report", url: "https://files.hawaii.gov/dlnr/reports-to-the-legislature/2026/LD26-Comprehensive-Economic-Analysis-of-All-Military-Leased-Lands-FY25.pdf" },
      { label: "BLNR Rejects EIS", url: "https://dlnr.hawaii.gov/blog/2025/05/10/nr25-71/" },
      { label: "Ka Wai Ola", url: "https://kawaiola.news/aina/the-army-and-pohakuloa/" },
      { label: "Fed Register EIS (2020)", url: "https://www.federalregister.gov/documents/2020/09/23/2020-20966/environmental-impact-statement-for-army-training-land-retention-at-phakuloa-training-area-in-hawaii" },
    ],
  },
  {
    id: "makua_leased",
    name: "Makua Military Reservation (State Lease)",
    island: "Oahu",
    acres: 1510,
    confidence: "hard",
    tenure: "state_leased",
    acquisitionYear: 1964,
    acquisitionMethod: "65-year lease from DLNR at $1 total (2 parcels)",
    startYear: 1964,
    leaseEnd: 2029,
    leaseCost: 1,
    cededLand: true,
    notes: "1,509.6 ac (2 parcels) per 1969 Table 9. DLNR 2026 shows ~782 ac in current tracts. BLNR rejected EIS June 2025.",
    zoning: "conservation",
    category: "leased",
    sources: [
      { label: "DLNR 2026 Leg Report", url: "https://files.hawaii.gov/dlnr/reports-to-the-legislature/2026/LD26-Comprehensive-Economic-Analysis-of-All-Military-Leased-Lands-FY25.pdf" },
      { label: "EO 11166 (Makua)", url: "https://www.presidency.ucsb.edu/documents/executive-order-11166-setting-aside-for-the-use-the-united-states-certain-public-lands-and" },
    ],
  },
  {
    id: "poamoho",
    name: "Kawailoa-Poamoho Training Area (State Lease)",
    island: "Oahu",
    acres: 4401,
    confidence: "hard",
    tenure: "state_leased",
    acquisitionYear: 1964,
    acquisitionMethod: "65-year lease from DLNR at $1 total (2 parcels)",
    startYear: 1964,
    leaseEnd: 2029,
    leaseCost: 1,
    cededLand: true,
    notes: "'Kawailewa' in 1964 lease (4,401.36 ac, 2 parcels) per 1969 Table 9. DLNR 2026: Poamoho (~3,170 ac) and NAR (~1,220 ac).",
    zoning: "conservation",
    category: "leased",
    sources: [
      { label: "DLNR 2026 Leg Report", url: "https://files.hawaii.gov/dlnr/reports-to-the-legislature/2026/LD26-Comprehensive-Economic-Analysis-of-All-Military-Leased-Lands-FY25.pdf" },
      { label: "Big Island Now (Nov 2025)", url: "https://bigislandnow.com/2025/11/28/military-leased-lands-panel-begins-laying-groundwork-for-future-talks-with-u-s-army/" },
    ],
  },
  {
    id: "kahuku",
    name: "Kahuku Training Area (State Lease)",
    island: "Oahu",
    acres: 1150,
    confidence: "hard",
    tenure: "state_leased",
    acquisitionYear: 1964,
    acquisitionMethod: "65-year lease from DLNR at $1 total (2 parcels)",
    startYear: 1964,
    leaseEnd: 2029,
    leaseCost: 1,
    cededLand: true,
    notes: "1,150 ac (2 parcels) per 1969 Table 9. North Shore Oahu.",
    zoning: "conservation",
    category: "leased",
    sources: [
      { label: "DLNR 2026 Leg Report", url: "https://files.hawaii.gov/dlnr/reports-to-the-legislature/2026/LD26-Comprehensive-Economic-Analysis-of-All-Military-Leased-Lands-FY25.pdf" },
      { label: "HPR: 30K Acres", url: "https://www.hawaiipublicradio.org/the-conversation/2021-08-25/military-leaders-30k-acres-of-land-national-security-state-training-diplomacy" },
    ],
  },
  {
    id: "pmrf_leased",
    name: "Pacific Missile Range Facility (State Lease)",
    island: "Kauai",
    acres: 2385,
    confidence: "firm",
    tenure: "state_leased",
    acquisitionYear: 1964,
    acquisitionMethod: "65-year lease from DLNR at $1 total",
    startYear: 1964,
    leaseEnd: 2029,
    leaseCost: 1,
    cededLand: true,
    notes: "Barking Sands. State-leased portion adjacent to federal parcel.",
    zoning: "military",
    category: "leased",
    sources: [
      { label: "OHA: Military Leased Lands", url: "https://www.oha.org/aloha-aina/" },
      { label: "HMLUMP 2021", url: "https://drive.google.com/file/d/1Uov0HevmHkfMG-ma-iEzxYgECHue67aY/view" },
    ],
  },
  {
    id: "kuaekala",
    name: "Kuaekala, Oahu (State Lease)",
    island: "Oahu",
    acres: 86,
    confidence: "hard",
    tenure: "state_leased",
    acquisitionYear: 1964,
    acquisitionMethod: "65-year lease from DLNR at $1 total (3 parcels)",
    startYear: 1964,
    leaseEnd: 2029,
    leaseCost: 1,
    cededLand: true,
    notes: "86.4 ac (3 parcels) per 1969 Table 9. Waianae range.",
    zoning: "conservation",
    category: "leased",
    sources: [
      { label: "1969 Historical Analysis, Table 9", url: "" },
      { label: "DLNR 2026 Leg Report", url: "https://files.hawaii.gov/dlnr/reports-to-the-legislature/2026/LD26-Comprehensive-Economic-Analysis-of-All-Military-Leased-Lands-FY25.pdf" },
    ],
  },
  {
    id: "lualualei_leased",
    name: "Lualualei, Oahu (State Lease)",
    island: "Oahu",
    acres: 58,
    confidence: "hard",
    tenure: "state_leased",
    acquisitionYear: 1964,
    acquisitionMethod: "65-year lease from DLNR at $1 total (2 parcels)",
    startYear: 1964,
    leaseEnd: 2029,
    leaseCost: 1,
    cededLand: true,
    notes: "57.825 ac (2 parcels) per 1969 Table 9. Adjacent to federal Naval Magazine Lualualei (8,200 ac).",
    zoning: "military",
    category: "leased",
    sources: [
      { label: "1969 Historical Analysis, Table 9", url: "" },
      { label: "DLNR 2026 Leg Report", url: "https://files.hawaii.gov/dlnr/reports-to-the-legislature/2026/LD26-Comprehensive-Economic-Analysis-of-All-Military-Leased-Lands-FY25.pdf" },
    ],
  },
];

// ═══════════════════════════════════════════════════════════════════════
// RENTAL RATE BENCHMARKS
// ═══════════════════════════════════════════════════════════════════════

export const BENCHMARKS = {
  conservation_low: { label: "Pasture (HI DoA 2024)", rate: 8.7, source: "HI Dept of Agriculture, 2024 avg cash rent for pasture: $8.70/ac" },
  agricultural: { label: "Cropland (HI DoA 2024)", rate: 326, source: "HI Dept of Agriculture, 2024 avg cash rent for cropland: $326/ac" },
  agricultural_irrigated: { label: "Irrigated Cropland (HI DoA 2024)", rate: 452, source: "HI Dept of Agriculture, 2024 avg cash rent for irrigated cropland: $452/ac" },
  usda_pacific: { label: "USDA Pacific Cropland (10% cap)", rate: 983, source: "USDA ERS 2025 Pacific region cropland: $9,830/ac x 10% cap rate" },
  market_median: { label: "Median HI Land Value (10% cap)", rate: 1136, source: "Land.com median HI price/ac $11,363 x 10% cap rate" },
  market_ag_tract: { label: "Ag Tract Value (10% cap)", rate: 740, source: "Large ag tract avg $7,400/ac (2020) x 10% cap rate" },
  market_high: { label: "Avg HI Land Value (2.5% cap)", rate: 5060, source: "Avg $202,400/ac x 2.5% cap rate (reflects dev potential)" },
  custom: { label: "Custom Rate", rate: 0, source: "User-defined" },
};

// ═══════════════════════════════════════════════════════════════════════
// CPI-U ANNUAL AVERAGE (BLS, 1982-84 = 100)
// Pre-1964 values from historical BLS tables. 2025-2026 projected.
// ═══════════════════════════════════════════════════════════════════════

export const CPI = {
  1887:8.2, 1898:8.6, 1900:8.8, 1907:9.6, 1908:9.5, 1916:10.9,
  1917:12.8, 1922:16.8, 1931:15.2, 1935:13.7, 1940:14.0, 1941:14.7,
  1942:16.3, 1943:17.3, 1956:27.2,
  1958:28.9, 1964:31.0, 1965:31.5, 1966:32.4, 1967:33.4, 1968:34.8,
  1969:36.7, 1970:38.8, 1971:40.5, 1972:41.8, 1973:44.4, 1974:49.3,
  1975:53.8, 1976:56.9, 1977:60.6, 1978:65.2, 1979:72.6, 1980:82.4,
  1981:90.9, 1982:96.5, 1983:99.6, 1984:103.9, 1985:107.6, 1986:109.6,
  1987:113.6, 1988:118.3, 1989:124.0, 1990:130.7, 1991:136.2, 1992:140.3,
  1993:144.5, 1994:148.2, 1995:152.4, 1996:156.9, 1997:160.5, 1998:163.0,
  1999:166.6, 2000:172.2, 2001:177.1, 2002:179.9, 2003:184.0, 2004:188.9,
  2005:195.3, 2006:201.6, 2007:207.3, 2008:215.3, 2009:214.5, 2010:218.1,
  2011:224.9, 2012:229.6, 2013:233.0, 2014:236.7, 2015:237.0, 2016:240.0,
  2017:245.1, 2018:251.1, 2019:255.7, 2020:258.8, 2021:271.0, 2022:292.7,
  2023:304.7, 2024:313.5, 2025:320.0, 2026:326.0,
};

// ═══════════════════════════════════════════════════════════════════════
// PRIMARY SOURCE DOCUMENTS (for methodology footer)
// ═══════════════════════════════════════════════════════════════════════

export const PRIMARY_SOURCES = [
  { label: "1969 Public Land Policy in Hawaii: An Historical Analysis — Table 9", url: "" },
  { label: "EO 11167: PTA (84,057 ac)", url: "https://www.presidency.ucsb.edu/documents/executive-order-11167-setting-aside-for-the-use-the-united-states-certain-public-lands-and" },
  { label: "EO 11166: Makua (3,236 ac)", url: "https://www.presidency.ucsb.edu/documents/executive-order-11166-setting-aside-for-the-use-the-united-states-certain-public-lands-and" },
  { label: "EO 11165: Fort Shafter", url: "https://www.presidency.ucsb.edu/documents/executive-order-11165-setting-aside-for-the-use-the-united-states-certain-public-lands-and" },
  { label: "EO 10436: Kahoolawe", url: "https://www.presidency.ucsb.edu/documents/executive-order-10436-reserving-kahoolawe-island-territory-hawaii-for-the-use-the-united" },
  { label: "Admission Act Sec 5(b), 5(d), 5(f)", url: "https://www.law.cornell.edu/topn/hawaii_admission_act" },
  { label: "PL 103-150: Apology Resolution (1993)", url: "https://www.congress.gov/bill/103rd-congress/senate-joint-resolution/19/text" },
  { label: "DLNR Report to 33rd Legislature (2026)", url: "https://files.hawaii.gov/dlnr/reports-to-the-legislature/2026/LD26-Comprehensive-Economic-Analysis-of-All-Military-Leased-Lands-FY25.pdf" },
  { label: "HMLUMP 2021", url: "https://drive.google.com/file/d/1Uov0HevmHkfMG-ma-iEzxYgECHue67aY/view" },
  { label: "Final EIS for PTA Retention (Apr 2025)", url: "https://www.federalregister.gov/documents/2025/04/18/2025-06686/final-environmental-impact-statement-for-army-training-land-retention-at-phakuloa-training-area-in" },
  { label: "PTA Record of Decision (Aug 2025)", url: "https://www.federalregister.gov/documents/2025/08/06/2025-14919/record-of-decision-for-army-training-land-retention-at-phakuloa-training-area-in-hawaii-id" },
  { label: "BLNR Rejects PTA EIS (May 2025)", url: "https://dlnr.hawaii.gov/blog/2025/05/10/nr25-71/" },
  { label: "OHA: Military Leased Lands", url: "https://www.oha.org/aloha-aina/" },
  { label: "HR 199 (2025)", url: "https://data.capitol.hawaii.gov/sessions/session2025/bills/HR199_.HTM" },
  { label: "Noho Hewa: Occupied Areas", url: "https://nohohewa.com/occupied-areas/" },
  { label: "Cultural Survival: Nation Under The Gun", url: "https://www.culturalsurvival.org/publications/cultural-survival-quarterly/nation-under-gun-militarism-and-resistance-hawaii" },
  { label: "HI GIS: DoD Lands Layer (2025)", url: "https://geodata.hawaii.gov/arcgis/rest/services/ParcelsZoning/MapServer/34" },
];

// ═══════════════════════════════════════════════════════════════════════
// CATEGORY METADATA
// ═══════════════════════════════════════════════════════════════════════

export const CATEGORIES = [
  { key: "federal", heading: "Federal-Owned Seized Ceded Lands", color: "#b44" },
  { key: "leased", heading: "State-Leased Ceded Lands ($1 / 65 years)", color: "#c8a96e" },
  { key: "returned", heading: "Returned Lands (Historical)", color: "#668" },
  { key: "custom", heading: "Custom Parcels", color: "#6a8" },
];

export const CATEGORY_COLORS = { federal: "#b44", leased: "#c8a96e", returned: "#668", custom: "#6a8" };
export const CATEGORY_LABELS = { federal: "FEDERAL-OWNED", leased: "STATE LEASE", returned: "RETURNED", custom: "CUSTOM" };

// Convenience: all built-in parcel IDs for default selection
export const ALL_PARCEL_IDS = PARCELS.map(function (p) { return p.id; });
